services:
  web:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    image: jwill9999/llama3.2-web:${VERSION:-latest}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
    - web

  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
    image: jwill9999/llama3.2-ollama:${VERSION:-latest}
    ports:
      - 11434:11434
    volumes:
      - ollama:/app/ollama
    networks:
     - web

networks:
  web:
    driver: bridge

volumes:
  ollama:
     driver: local

